repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.9.3'
    hooks:
      - id: ruff
        args: ['--fix']
  
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    - id: black
      language_version: python3
# Mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.14.1'  
    hooks:
    - id: mypy 
      args: [--ignore-missing-imports]
      name: mypy 
      additional_dependencies: [types-PyYAML==6.0.12.20240808, types-requests==2.32.0.20241016
      ,annotated-types==0.7.0,pydantic,pydantic_core,types-tabulate]
      files: ^src/
