dask_cluster:
  netcdf_work: # threads per worker set to deal with https://forum.access-hive.org.au/t/netcdf-not-a-valid-id-errors/389
    n_workers: None  # Number of workers for default cluster
    threads_per_worker: 1  # threads per worker set to deal with https://forum.access-hive.org.au/t/netcdf-not-a-valid-id-errors/389
    memory_limit: 0  # Default memory limit per worker
  bwmega_work: # threads per worker set to deal with https://forum.access-hive.org.au/t/netcdf-not-a-valid-id-errors/389
    n_workers: 8  # Number of workers for default cluster
    threads_per_worker: 1  # threads per worker set to deal with https://forum.access-hive.org.au/t/netcdf-not-a-valid-id-errors/389
    memory_limit: None  # Default memory limit per worker
  zarr_work:
    n_workers: None  # Number of workers for default cluster
    threads_per_worker: None  # Default threads per worker
    memory_limit: 0  # Default Memory limit per worker
catalog_search_query_dict:
  ACCESS_ESM15:
    all_ocean:
      NCI_catalog:
        realm: ['ocean','ocnBgchem']
        source_id: 'ACCESS-ESM1-5'
    CSEPTA:
      NCI_catalog:
        experiment_id: ['piControl'] #,'historical','ssp370']
        source_id: 'ACCESS-ESM1-5'
        variable_id: ['intpp']
        realm: ['ocean','ocnBgchem']
        frequency: 'mon'
        file_type: 'l'
      CLEX_catalog:
        experiment_id: ['piControl'] #,'historical','ssp370']
        source_id: 'ACCESS-ESM1-5'
        variable_id: ['u']
        table_id: 'Omon'
load_data:
  GOBAI_O2:
    climatology:
      kwargs: None
      path: '/g/data/es60/data/raw-data/in-situ-obs/GOBAI-O2/4.4/data/0-data/GOBAI-O2-clim-v2.2.nc'
    monthly:
      kwargs: None
      path: '/g/data/es60/data/raw-data/in-situ-obs/GOBAI-O2/4.4/data/0-data/GOBAI-O2-v2.2.nc'
chunking:
  ACCESS_ESM15_2D: #{'chunks':{'member':1,'time':220,'j':300,'i':360}}
    chunks:
      member: 1
      time: 220
      i: 360
      j: 300
  ACCESS_ESM15_3D: #{'chunks':{'member':?,'time':?,'lev':-1,'j':-1,'i':-1}}
    chunks:
      member: 1
      time: 12
      lev: -1
      i: -1
      j: -1
lon_lat_locations:
  WCPFC:
    latitudes: [
    -21.236,  # Cook Islands
     6.887,   # Federated States of Micronesia
    -17.713,  # Fiji
     1.870,   # Kiribati
    -0.522,   # Nauru
    -19.054,  # Niue
     7.514,   # Palau
    -6.314,   # Papua New Guinea
     7.131,   # Republic of Marshall Islands
    -13.759,  # Samoa
    -9.645,   # Solomon Islands
    -21.179,  # Tonga
    -7.109,   # Tuvalu
    -15.376,  # Vanuatu
    -14.271,  # American Samoa
    15.213,   # Commonwealth of the Northern Mariana Islands
    -17.679,  # French Polynesia
    13.444,   # Guam
    -21.244,  # New Caledonia
    -9.200,   # Tokelau
    -13.300   # Wallis and Futuna
    ]
    longitudes: [
    -159.777,  # Cook Islands
    158.186,   # Federated States of Micronesia
    178.065,   # Fiji
    -157.363,  # Kiribati
    166.931,   # Nauru
    -169.867,  # Niue
    134.582,   # Palau
    143.955,   # Papua New Guinea
    171.184,   # Republic of Marshall Islands
    -172.104,  # Samoa
    160.156,   # Solomon Islands
    -175.198,  # Tonga
    179.194,   # Tuvalu
    167.962,   # Vanuatu
    -170.132,  # American Samoa
    145.750,   # Commonwealth of the Northern Mariana Islands
    -149.406,  # French Polynesia
    144.793,   # Guam
    165.618,   # New Caledonia
    -171.847,  # Tokelau
    -176.194   # Wallis and Futuna
    ]
    labels: [
    "Cook Islands",
    "Micronesia",
    "Fiji",
    "Kiribati",
    "Nauru",
    "Niue",
    "Palau",
    "Papua New Guinea",
    "Marshall Islands",
    "Samoa",
    "Solomon Islands",
    "Tonga",
    "Tuvalu",
    "Vanuatu",
    "American Samoa",
    "Northern Mariana Islands",
    "French Polynesia",
    "Guam",
    "New Caledonia",
    "Tokelau",
    "Wallis and Futuna"
    ]
plotting:
  CSEPTA:
    path_for_savefig: '/g/data/es60/users/thomas_moore/plots/CSEPTA/'